# Generated by Django 4.0.4 on 2022-04-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_musician_participant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('person', 'project')},
        ),
    ]
